### ISSUE TITLE
Determine the extent of AWS Guardduty deployment and management

### ISSUE THREAD

**Issue by JJediny** [18F/aws-admin#103]
## Background Information

Implementation of https://github.com/18F/tts-tech-portfolio/issues/739

## Implementation Steps
Convene TTS Programs to :
- [ ] recommend GuardDuty for production and staging environments for TTS System owners (Based on pricing this is worth the investment if tuned well).
- [ ] present on Cloud Custodian's guardian as a potential offering to TTS System to co-develop events to alerts for and automate its deployment - based ongoing lessons learned from the login.gov team (which is actively using it).

## Acceptance Criteria

- [ ] List of TTS Programs intending to use Guardduty are known.
- [ ] Determination of Tech Portfolio's involvement in developing/maintaining a central managed service for the setup/rulesets/alerts using terraform/Cloudcustodian is known.
- [ ] Issue created for any follow up tasks.
