### ISSUE TITLE
restrict what AWS services can be used

### ISSUE THREAD

**Issue by afeld** [18F/aws-admin#104]
## Background Information

GSA has [a certain set of AWS services that are approved for use](https://docs.google.com/spreadsheets/d/1kJrPqu10x80LaGQ_oXFDuoPkBdnaXrXTQVF_uJ14-ok/edit#gid=0). While [we say in Before You Ship](https://before-you-ship.18f.gov/infrastructure/aws/#building-systems-that-will-be-deployed-directly-to-aws) that only those approved services should be used, it's easier all around if they are restricted through a technical control.

I had written some code for GRACE to generate to generate [Service Control Policies (SCPs)](https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_scps.html). It was since removed from that repository — [asking if it moved somewhere](https://github.com/GSA/security-benchmarks/pull/37/files?short_path=b335630#r533695119) — but [here's the old README and code](https://github.com/GSA/security-benchmarks/blob/227754fcb71e4a8c416ab4a8b87dd3664aa0723e/scp/README.md).

## Implementation Steps
- [ ] Determine if this should apply to all AWS accounts, or just production ones
- [ ] Try out that code and see what it would take to make it work
- [ ] Move that code+documentation into this repository
- [ ] `apply` the changes

## Acceptance Criteria

- [ ] When a user tries to create a new instance of a service that isn't allowed, they get an error

**Comment by afeld** [comment]
https://github.com/salesforce/aws-allowlister
