### ISSUE TITLE
Rollout of consolidated IAM users - role management

### ISSUE THREAD

**Issue by amitfreeman-gov** [18F/aws-admin#110]
## Background Information

As the gatekeepers for the tech-portfolio-mastered IAM accounts, we need to better understand how users of this service would leverage such a model.  The overarching objective is to understand how the teams envision managing assumeable roles within their accounts, how granular those roles will be with respect to permissions, and how ongoing management/maintenance will be handled.

The related breaking-ground issue that laid down the tech-portfolio source account-side is [aws-admin/39](https://github.com/18F/aws-admin/issues/39)

## Implementation Steps
- [ ] Solicit feedback from programs with regards to destination account roles
- [ ] Implement a tag-based mechanism to automatically detect target account roles and apply the appropriate policy in the source account

## Acceptance Criteria
- [ ] A tool exists that runs at a set interval (or fancier, a cloudtrail-triggered one that watches role tags) and keeps the source STS assume-role permissions up-to-date with the program roles
- [ ] A document exists that generally highlights agreements with regards to how the programs will leverage the roles
- [ ] A pilot program team is selected to begin testing a rollout

**Comment by JJediny** [comment]
AWS came back with confirmation that AWS SSO is only available through AWS Orgs but provided the following workaround

 

WORKAROUND =========== However, I can suggest a workaround for logging in to AWS Management Console of a linked/member account using IAM Identity providers with SAML 2.0-based federation [3]. You can use IAM identity provider to establish between a SAML-compatible external IDP with AWS to enable users in the external IDP to access resources in your AWS account using their external credentials. This option allows you to use any SAML 2.0 or ODIC-compatible IDPs [4] to grant users access to your AWS resources without leveraging on AWS Organizations. I hope you find the above information helpful. In case you need any further clarification or have more questions/concerns, please feel free to reply to this case and I'll be more than happy to assist you. Take care, stay safe and happy Cloud Computing! REFERENCES ========== [1] AWS SSO Prerequisites - https://docs.aws.amazon.com/singlesignon/latest/userguide/prereqs.html [2] Manage your identity source - https://docs.aws.amazon.com/singlesignon/latest/userguide/manage-your-identity-source.html [3] About SAML 2.0-based federation - https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_saml.html [4] Creating IAM Identity Providers - https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create.html [5] Enabling SAML 2.0 federated users to access the AWS Management Console - https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_enable-console-saml.html
