### ISSUE TITLE
AWS IAM Permission tightening

### ISSUE THREAD

**Issue by amitfreeman-gov** [18F/aws-admin#111]
## Background Information

As stakeholders in the management of AWS accounts, we would provide additional security and a better understanding of what our accounts and services are doing by paring down unused permissions in our AWS accounts.

Following aws-admin/23, we have, and may generate new, airiam reports showing the extent to which access is overly broad.  

The related issue implementing AIRIAM to audit the use of granted permissions is [aws-admin/23](https://github.com/18F/aws-admin/issues/23)

## Implementation Steps
- [ ] Speak with program teams to identify general concerns regarding access-breadth
- [ ] Select a pilot team to work with to begin paring down access

## Acceptance Criteria

- [ ] A document exists highlighting the relevant concerns within the teams with respect to access granted / overhead
- [ ] A pilot team is selected to work to pare down access in new groups, which we can switch them over to
- [ ] The same new groups that are created are mirrored into assumable roles to facilitate migration to the federated AWS account users
