### ISSUE TITLE
Automate terraform-docs generation

### ISSUE THREAD

**Issue by JJediny** [18F/aws-admin#113]
## Background Information

Automate the docs/var/input/outputs 

## Implementation Steps
- [ ] Add [terraform-docs.yml file to repo](https://github.com/terraform-docs/terraform-docs/blob/master/docs/CONFIG_FILE.md)
- [ ] Generate, move, cleanup current docs into terraform-docs generated README.

- [ ] Determine which to do for maintaining:
   - [ ] 1. Add to [.git/hooks/pre-commit](https://github.com/terraform-docs/terraform-docs/blob/master/docs/USER_GUIDE.md#integrating-with-your-terraform-repository)
   - [ ] 2. Enable [github action](https://github.com/marketplace/actions/setup-terraform-docs) or circleci to create an automated commit w/ doc updates to open PRs

## Acceptance Criteria

- [ ] terraform-docs are being generated and updated as part of the standard PR process.
