### ISSUE TITLE
Setup an Automated CIS Benchmark Scan for all managed AWS accounts

### ISSUE THREAD

**Issue by JJediny** [18F/aws-admin#114]
MITRE has developed a set of inspec benchmarks mapped to NIST Controls. There is also https://github.com/devsec profiles, both has complimentary terraform hardening modules.

## Implementation Steps
- [ ] Setup inspec to run as part of CI against all accounts as a:
   - [ ] CRON runner
   - [ ] part of the standard PR (might be too long to run each time)
- [ ] Determine how to best store/track/display test results
   - [ ] consider deploying https://github.com/mitre/heimdall2 as a cloud.gov app to serve as a `{{ account }}-{{ timestamp }}.json` endpoint to save and diff results over time
   - [ ] forgo tracking and just invest in upfront remediation to assume 100% pass

## AC
- [ ] AWS CIS Benchmark status is known and tracked continuously for all managed accounts

**Comment by afeld** [comment]
Let's scope this down to a proof-of-concept:

- Timebox it
- See what kind of results we get and how actionable we think they are
- Kick the "run as part of CI" part to a follow-up issue
- etc.
