### ISSUE TITLE
Alert on root account usage

### ISSUE THREAD

**Issue by afeld** [18F/aws-admin#12]
...across the various accounts.

- https://aws.amazon.com/blogs/mt/monitor-and-notify-on-aws-account-root-user-activity/
- https://docs.aws.amazon.com/en_pv/awscloudtrail/latest/userguide/cloudwatch-alarms-for-cloudtrail-additional-examples.html#cloudwatch-alarms-for-cloudtrail-root-example
- https://cloudcustodian.io/docs/aws/examples/accountrootlogin.html cc #17 

### Implementation Steps
- [x] Implement slack alert
- [x] Implement optional email alert
- [x] Test
- [x] Rollout to all TTS accounts

### Acceptance Criteria
- [x] Tech Portfolio and relevant program team (if applicable) is notified when root AWS account is used.

**Comment by afeld** [comment]
I'd clarify the Acceptance Criteria as "Tech Portfolio and relevant program team (if applicable) is notified when root AWS account is used."

**Comment by its-a-lisa-at-work** [comment]
Agree with @afeld suggestion above

**Comment by JJediny** [comment]
We're going with this https://cloudcustodian.io/docs/aws/examples/accountrootlogin.html coupled with https://github.com/GSA/grace-cloudcustodian

**Comment by JJediny** [comment]
moved from cloudcustodian to https://github.com/gsa/grace-alerts 

Implemented and rolled out across managed accounts - https://gsa-tts.slack.com/archives/CPHL3456Z/p1608331877007800
