### ISSUE TITLE
Implement a technical solution for terraform secrets management

### ISSUE THREAD

**Issue by JJediny** [18F/aws-admin#122]
## Background Information

In order to enable CI/CD we need to agree on an acceptable solution for storing/accessing secrets

## Implementation Steps

- [x] Reach out to login.gov to find out how they do it
- [ ] Document an implemented architecture
- [ ] Implement

## Acceptance Criteria

- [ ] Documented secrets management for CI/CD 
- [ ] Secrets are managed in an acceptable manner that has been shared with security.

**Comment by afeld** [comment]
Related issue around TTS-wide documentation: https://github.com/18F/handbook/issues/2360

**Comment by adborden** [comment]
Getting started on this. We're going to need an IAM "bot" user and credentials for CI/CD. From what I can tell, we currently manage IAM users manually? How about I create a (private) 18f/tts-iam repo to handle IAM users, include this bot account and it's permissions?

As part of data.gov, we found that it was helpful to keep IAM separate from other infrastructure (e.g. 18f/aws-admin).

**Comment by afeld** [comment]
I personally think managing users manually is fine, but if we do want to manage in code, suggest we re-purpose https://github.com/18F/aws-admin-cleanup.

**Comment by adborden** [comment]
@afeld 👍  do you make a distinction between managing users vs IAM roles/groups/policies? I can imagine having the IAM permissions for a bot policy to be good to have under configuration-as-code, even if it's manual to assign admin users and bot accounts to those policies.

**Comment by afeld** [comment]
Rather than try to solve in the abstract, we will address as part of https://github.com/18F/newrelic-terraform/issues/16 / https://github.com/18F/aws-admin/issues/151 / https://github.com/18F/tts-tech-portfolio/issues/443.

**Comment by JJediny** [comment]
>Rather than try to solve in the abstract, we will address as part of 18F/newrelic-terraform#16 / #151 / 18F/tts-tech-portfolio#443.

I think we could better do this as suggested ^. I've created a [CRM crosswalk](https://docs.google.com/spreadsheets/d/1L2v1ZMlSscDgDMlDu1xvuH48HRDxnxHU3heFxtFq8RI/edit#gid=910638200) for all 3 CSPs we have access to (AWS/Azure/GCP) and Cloud.gov. If we were to go through each row and write up a `planned implementation` for the common controls.
