### ISSUE TITLE
investigate use of AWS Control Tower

### ISSUE THREAD

**Issue by afeld** [18F/aws-admin#123]
## Background Information

> AWS Control Tower provides the easiest way to set up and govern a new, secure, multi-account AWS environment based on best practices

https://aws.amazon.com/controltower/

Might make some of our account setup and configuration easier.

## Implementation Steps
- [x] Get presentation from AWS
- [x] Login.gov: Determine if they want/plan to use it
- [x] Determine if it needs to be rolled out Organization-wide, or if it can be used for specific accounts

## Acceptance Criteria

- [x] 👍 / 👎 on whether to pursue use of Control Tower TTS-wide
- [x] Follow-up issues created

**Comment by afeld** [comment]
[From Slack:](https://gsa-tts.slack.com/archives/C029KQMBZ/p1610553147001600?thread_ts=1610497127.000700&cid=C029KQMBZ)

> Control tower would be helpful to projects that use the account boundary and need templated `dev` `staging` etc accounts, and pre-populated to aggregate logs to a SecOps account, or guard duty cross account IAM by default

**Comment by JJediny** [comment]
Control Tower is too rigid at this time to utilize, it currently doesn't support cloudwatch/cloudtrail customization which was the most interesting aspect. All other functionality can be easily emulated with terraform standard configuration. No follow up issue required, will reassess in the future if capabilities improve.
