### ISSUE TITLE
include sandbox in config

### ISSUE THREAD

**Issue by afeld** [18F/aws-admin#137]
## Background Information

We don't have the `tts-sandbox` account included in the Terraform configuration.

## Implementation Steps

- [ ] `account` module used
- [ ] `account_setup` module used
- [ ] Roles configured

## Acceptance Criteria

- [ ] All `tts-sandbox` account configuration (besides the usernames) is managed via Terraform
