### ISSUE TITLE
Document how to securely manage AWS credentials for local development

### ISSUE THREAD

**Issue by adborden** [18F/aws-admin#147]
## Background Information

In order to conform to GSA and TTS compliance for managing secrets in local development, aws-admin developers want the README to be updated with a secure method for managing AWS credentials.

The setup instructions use the [plain text credentials file](https://blog.gruntwork.io/authenticating-to-aws-with-the-credentials-file-d16c0fbcbf9e) for configuring AWS credentials. The article itself describes this as not being secure.

## Implementation Steps

- [ ] Identify a tool or strategy for managing secrets through the OS keychain or environment
- [ ] Update README with new instructions
- [ ] If any migration from the existing credentials is necessary, those migration instructions should be provided to other team members

## Acceptance Criteria

- [ ] WHEN I follow the README instructions for 18f/aws-admin
   THEN my AWS credentials are stored encrypted at rest
