### ISSUE TITLE
track budgeting and spending

### ISSUE THREAD

**Issue by afeld** [18F/aws-admin#19]
## Background

Related to [how to create accounts](https://github.com/18F/tts-tech-portfolio/issues/136) is how to handle changes in spend, intentional and unintentional.

## User stories

- As someone managing the AWS budget/contract, I want to ensure that we don't get (close to) deficient on our AWS contract.

## TODOs

- [x] Determine if budget amounts are considered sensitive, and therefore if they can go into the code directly or should be pulled from elsewhere
- [x] Set up [budget alerts](https://aws.amazon.com/aws-cost-management/aws-budgets/) - #18 may help
- [x] Document that anticipated major changes to burn rates should be run by the Contracting Officer Representative (@JJediny) so that we ensure we aren't going to overrun budgets - https://github.com/18F/before-you-ship/pull/423

## Links

- [Slack thread](https://gsa-tts.slack.com/archives/G90GHVCKZ/p1573130860035800)
- [Spending per business unit over time data and chart](https://docs.google.com/spreadsheets/d/1DedSCiU9AsCAAVvAFZT0_Ii7AFIKlI-JNifzlpHNbDg/edit#gid=2122233389)
- [List of purchase requests](https://docs.google.com/spreadsheets/d/1G6umo-xENwiK4zX3Ospgmwkk9cj6Oh0GvKJbyEG3TDo/edit#gid=60391608)

**Comment by JJediny** [comment]
@afeld suggest closing as we have basic alerts in place and have full insight into spend as of today.

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.
