### ISSUE TITLE
As the TTS Tech Portfolio, we need to be able to troubleshoot AWS accounts

### ISSUE THREAD

**Issue by afeld** [18F/aws-admin#24]
We had [an incident](https://github.com/18F/Infrastructure/issues/920) come up recently, and had trouble tracking down what account the issue was coming from, what it was being used for, who had access to it, and how to get others access to it. Thankfully the incident was a relatively minor one, but something more serious will inevitably come up, and this disorganization will be a major problem.

- [x] Get [CloudCheckr](https://app.cloudcheckr.com/Projects#!/projects) access
- [x] Get into accounts - 18F/tts-tech-portfolio#54 
- [x] Decide on the source of truth for the questions in 18F/tts-tech-portfolio#27, but specific to AWS accounts
- [x] Figure out how to better handle cross-account admin access - 18F/tts-tech-portfolio#65
- [ ] Create a run/play book for troubleshooting AWS accounts

See also:

- [cloud.gov AWS account internal documentation](https://docs.google.com/document/d/110o1L7EOby3hvE5d-cDhg2LBLHymbZLnMPe9kuk4qp8/edit)

**Comment by afeld** [comment]
Calling this done.

https://github.com/18F/aws-admin#cross-account-access
