### ISSUE TITLE
Remove stale/offboarded AWS users 

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/aws-admin#43]
## Background information

Broken out from https://github.com/18F/aws-admin/issues/40

## User stories
As a tech portfolio member I want to know we have atleast a one-time holistic cleanup for users within all AWS accounts

## Implementation Steps

- [x] All stale invitation are removed
- [x] All users that need to be offboarded are
- [ ] Export a full list of users with:
   -  Username/Email
   -  Account(s)
   -  Roles/Permissions/Group membership per account.
- [ ] list per account provided to budget/program responsible for their accounts
- [ ] Create a new issue for any accounts not audited

## Acceptance criteria

- [x] Users that no longer need TTS AWS access have been removed

**Comment by its-a-lisa-at-work** [comment]
Where would the list of exported lists go?

**Comment by afeld** [comment]
I'd simplify Acceptance Criteria to "Users that no longer need TTS AWS access have been removed."

**Comment by afeld** [comment]
Went into each AWS account and manually deleted users that have offboarded or have `Last Activity` greater than 100 days or so ago. We should have some automation to check for the latter, but considering this done for now.
