### ISSUE TITLE
Identify unused resources

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/aws-admin#45]
## Background information

…that cost money. Focus on low-hanging fruit, such as:

- RDS instances without connection
- EC2 instances without CPU usage or network traffic

over time. Broken out from https://github.com/18F/aws-admin/issues/40.

## User stories
As a tax payer we want to make sure we are not wasting un/under utilized services already provisioned/running.

## Implementation Steps

- [x] Create list for all ~unused resources are identified
- [x] email/slack teams (per budget) with listing/results
internally)
- [x] Create a new issue for any accounts not audited

## Acceptance criteria

- [x] Teams are aware of expensive resources they have running in their accounts, for a small list of services as a one-time thing.

**Comment by JJediny** [comment]
New issue should be created to track responses - 

- [ ] confirm list reviews and deletions made w/ final confirmation

**Comment by afeld** [comment]
The current Acceptance Criteria work as implementation steps; I would simplify the Acceptance Criteria to "Teams are aware of expensive resources they have running in their accounts, for a small list of services as a one-time thing."

**Comment by JJediny** [comment]
Based on the analysis of resources we (tech portfolio managed AWS accounts - not including cloud.gov/login.gov) there are no major underutilized ec2, s3, nor RDS instances based on the cloud custodian audit.

**Comment by afeld** [comment]
Great (albeit surprising) news!

**Comment by afeld** [comment]
@JJediny @amitfreeman-gov Where's the code for this?

**Comment by afeld** [comment]
Answer is https://github.com/18F/aws-admin/pull/95.
