### ISSUE TITLE
Enforce 2FA/MFA for AWS IAM jump account users

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/aws-admin#47]
## Background information

Broken out from https://github.com/18F/aws-admin/issues/40

## Implementation steps

- [x] Add condition to all IAM policies to require MFA

## Acceptance criteria

- [ ] IAM users are unable to do anything besides set up MFA if they don't have MFA set up
- [ ] Documented process for handling users who lose their MFA

**Comment by pburkholder** [comment]
We're doing this now to enforce at the CLI level, let me know if you need help when you get to this. --Peter

**Comment by adborden** [comment]
Data.gov uses this [policy](https://github.com/GSA/datagov-infrastructure-live/blob/master/iam/files/aws_sec_creds_self_manage.json) wrapped in terraform. Would be neat if it was maintained at the TTS level.

**Comment by afeld** [comment]
login.gov maintains [a Terraform module](https://github.com/18F/identity-terraform/blob/master/iam_masterusers/README.md) that covers this, which should be looked at as well.

**Comment by pburkholder** [comment]
[cloud.gov policy ](https://github.com/cloud-gov/cg-provision/blob/master/terraform/modules/iam_role_policy/self_managed_credentials/policy.json) pretty close to Data.gov's.

**Comment by afeld** [comment]
Going to do https://github.com/18F/aws-admin/issues/39 first to make this easier.

**Comment by afeld** [comment]
Will likely be completed as part of https://github.com/18F/aws-admin/issues/110.
